name: Deploy Django Application to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/deployment_key
        chmod 600 ~/.ssh/deployment_key
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/deployment_key
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      env:
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
      run: |
        ssh -i ~/.ssh/deployment_key ec2-user@$EC2_PUBLIC_IP << 'EOF'
          # Your deployment commands here
          sudo systemctl stop nginx
          sudo systemctl stop gunicorn

          cd /home/ubuntu/django_rest_project_management_api
          git pull origin master

          source /home/ubuntu/django_rest_project_management_api/project_management_system/venv/bin/activate
          cd /home/ubuntu/django_rest_project_management_api/project_management_system
          pip install -r requirements.txt
          python manage.py makemigrations
          python manage.py migrate
          python manage.py collectstatic --noinput

          sudo systemctl start nginx
          sudo systemctl start gunicorn
        EOF