name: Deploy Django Application to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure SSH
      env:
        SSH_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/deploy_key
        echo "Added key to SSH agent"

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_PUBLIC_IP }}
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ubuntu@$HOST << 'EOF'
          cd /home/ubuntu/django_rest_project_management_api
          git pull origin master

          source /home/ubuntu/django_rest_project_management_api/project_management_system/venv/bin/activate
          cd /home/ubuntu/django_rest_project_management_api/project_management_system
          pip install -r requirements.txt
          python manage.py makemigrations
          python manage.py migrate
          python manage.py collectstatic --noinput

          sudo systemctl restart nginx
          sudo systemctl restart gunicorn
        EOF