name: Deploy Django Application to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 3: Debug SSH Connection (to ensure it works correctly)
    - name: Debug SSH Connection
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        eval $(ssh-agent -s)  # Start the SSH agent
        ssh-add private_key.pem  # Add the private key to the agent
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} "echo 'SSH connected successfully!'"

    # Step 2: Set up SSH access to EC2 instance
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}



    # Step 4: SSH into EC2 instance and stop services, pull changes, migrate, collectstatic, restart services
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Step 4a: Stop Nginx and Gunicorn services
          sudo systemctl stop nginx
          sudo systemctl stop gunicorn

          # Step 4b: Go to project directory and pull the latest code
          cd /home/ubuntu/django_rest_project_management_api
          git pull origin master

          # Step 4c: Go to the project management directory for migrations and collectstatic
          # Activate virtual environment
          source /home/ubuntu/django_rest_project_management_api/project_management_system/venv/bin/activate
          cd /home/ubuntu/django_rest_project_management_api/project_management_system
          pip install -r requirements.txt
          python manage.py makemigrations
          python manage.py migrate
          python manage.py collectstatic --noinput

          # Step 4d: Restart Nginx and Gunicorn services
          sudo systemctl start nginx
          sudo systemctl start gunicorn
        EOF
